In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
print(tf.__version__)

2.12.0


In [3]:
#Initialization of tensorflow
x=tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
x=tf.constant(4)
print(x.numpy())

4


In [5]:
a=np.random.randn(4,5)
a=tf.constant(a)
for i in a:
    print(i.numpy())

[ 0.06814012 -0.35619025  0.47746957  0.37928795  0.79835447]
[-0.3127321   0.73555231  1.15646072  2.70524559 -0.15345322]
[ 1.01805331  1.66575564  1.27230332 -1.79756535  0.4180273 ]
[-0.19864753 -2.11225808  1.33780049 -0.86353541  0.21518045]


In [6]:
df=pd.DataFrame(a)
df

0         1         2         3         4
0  0.068140 -0.356190  0.477470  0.379288  0.798354
1 -0.312732  0.735552  1.156461  2.705246 -0.153453
2  1.018053  1.665756  1.272303 -1.797565  0.418027
3 -0.198648 -2.112258  1.337800 -0.863535  0.215180

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [8]:
x=scaler.fit_transform(df)
x

array([[-0.14437377, -0.24146162, -1.70075197,  0.16200615,  1.3915978 ],
       [-0.87208069,  0.53523231,  0.27819995,  1.54012768, -1.37460561],
       [ 1.67056144,  1.19700305,  0.61582871, -1.1277716 ,  0.28626704],
       [-0.65410698, -1.49077374,  0.80672332, -0.57436222, -0.30325923]])

In [9]:
tf.constant(x)

<tf.Tensor: shape=(4, 5), dtype=float64, numpy=
array([[-0.14437377, -0.24146162, -1.70075197,  0.16200615,  1.3915978 ],
       [-0.87208069,  0.53523231,  0.27819995,  1.54012768, -1.37460561],
       [ 1.67056144,  1.19700305,  0.61582871, -1.1277716 ,  0.28626704],
       [-0.65410698, -1.49077374,  0.80672332, -0.57436222, -0.30325923]])>

In [10]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [11]:
x=tf.constant([[1,2,3],[4,5,6]],shape=(2,3))
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [12]:
x=tf.ones((3,3),dtype=tf.int32)
print(x)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [13]:
x=tf.zeros((3,3),dtype=tf.int32)
print(x)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)


In [14]:
x=tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [15]:
x=tf.random.normal((3,3))
print(x)

tf.Tensor(
[[ 0.546477   -0.2466955  -0.5643585 ]
 [ 0.8948932  -0.18124992  1.0002548 ]
 [ 0.638396   -1.2448225   2.0352404 ]], shape=(3, 3), dtype=float32)


In [16]:
x=tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[ 0.238706    1.0111995   0.57688904]
 [-0.75817126 -1.4044166  -0.8513855 ]
 [ 0.16070725 -0.27968076 -0.404821  ]], shape=(3, 3), dtype=float32)


In [17]:
x=tf.random.uniform((3,3),minval=0,maxval=1)
print(x)

tf.Tensor(
[[0.8339881  0.5215746  0.6581894 ]
 [0.5042287  0.9202895  0.6771647 ]
 [0.21728063 0.7522352  0.3296342 ]], shape=(3, 3), dtype=float32)


In [18]:
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [19]:
x=tf.range(start=1,limit=10,delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [20]:
x=tf.cast(x,dtype=tf.float32)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float32)


In [21]:
#Mathematical Operations
x=tf.constant([6,5,7,8],dtype=tf.int32)
y=tf.constant([8,9,7,30],dtype=tf.int32)

In [22]:
z=tf.add(x,y)
print(z)

tf.Tensor([14 14 14 38], shape=(4,), dtype=int32)


In [23]:
z=x+y
print(z)

tf.Tensor([14 14 14 38], shape=(4,), dtype=int32)


In [24]:
z=tf.subtract(x,y)
print(z)

tf.Tensor([ -2  -4   0 -22], shape=(4,), dtype=int32)


In [25]:
z=x-y
print(z)

tf.Tensor([ -2  -4   0 -22], shape=(4,), dtype=int32)


In [26]:
z=tf.divide(x,y)
print(z)

tf.Tensor([0.75       0.55555556 1.         0.26666667], shape=(4,), dtype=float64)


In [27]:
z=x/y
print(z)

tf.Tensor([0.75       0.55555556 1.         0.26666667], shape=(4,), dtype=float64)


In [28]:
z=tf.multiply(x,y)
print(z)

tf.Tensor([ 48  45  49 240], shape=(4,), dtype=int32)


In [29]:
z=x*y
print(z)

tf.Tensor([ 48  45  49 240], shape=(4,), dtype=int32)


In [30]:
z=tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor(382, shape=(), dtype=int32)


In [31]:
z=tf.reduce_sum(x*y,axis=0)
print(z)

tf.Tensor(382, shape=(), dtype=int32)


In [32]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))

In [33]:
z=tf.matmul(x,y)
print(z)

tf.Tensor(
[[-2.9417462   1.1397016  -3.113196    0.68753886]
 [ 0.59223026 -1.9907857   1.5056732  -0.42881826]], shape=(2, 4), dtype=float32)


In [34]:
#Indexing
x=tf.constant([0,1,1,2,3,2,3,4,5,4,5,6,7,8,9])
print(x)

tf.Tensor([0 1 1 2 3 2 3 4 5 4 5 6 7 8 9], shape=(15,), dtype=int32)


In [35]:
x[:]

<tf.Tensor: shape=(15,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 2, 3, 4, 5, 4, 5, 6, 7, 8, 9])>

In [36]:
x[1:4]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 1, 2])>

In [37]:
x=tf.constant([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [38]:
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [39]:
x[1:3,1:3]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [8, 9]])>

In [40]:
x[2,2]

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [41]:
#Reshaping
x=tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [42]:
x=tf.reshape(x,shape=(3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [51]:
tf.matrics('1,2,3;4,5,6;7,8,9')

AttributeError: module 'tensorflow' has no attribute 'matrics'