# Lowercasing

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('spam_ham_dataset.csv')

In [3]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [4]:
df['text'][0]

"Subject: enron methanol ; meter # : 988291\r\nthis is a follow up to the note i gave you on monday , 4 / 3 / 00 { preliminary\r\nflow data provided by daren } .\r\nplease override pop ' s daily volume { presently zero } to reflect daily\r\nactivity you can obtain from gas control .\r\nthis change is needed asap for economics purposes ."

In [5]:
df['text'][0].lower()

"subject: enron methanol ; meter # : 988291\r\nthis is a follow up to the note i gave you on monday , 4 / 3 / 00 { preliminary\r\nflow data provided by daren } .\r\nplease override pop ' s daily volume { presently zero } to reflect daily\r\nactivity you can obtain from gas control .\r\nthis change is needed asap for economics purposes ."

In [6]:
def lower(text):
    return text.lower()

In [7]:
df['text']=df['text'].apply(lower)
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  subject: photoshop , windows , office . cheap ...   
4        2030   ham  subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

# Inflect libraries

In [8]:
df['text'][0]

"subject: enron methanol ; meter # : 988291\r\nthis is a follow up to the note i gave you on monday , 4 / 3 / 00 { preliminary\r\nflow data provided by daren } .\r\nplease override pop ' s daily volume { presently zero } to reflect daily\r\nactivity you can obtain from gas control .\r\nthis change is needed asap for economics purposes ."

In [9]:
import inflect
a=inflect.engine()
new_str=[]
def num_to_word(text):
#     temp_string=text.split()
    for word in  text.split():
        if word.isdigit():
            temp=a.number_to_words(word)
            new_str.append(temp)
        else:
            new_str.append(word)
    full_string=' '.join(new_str)
    return full_string
text=df['text'][0]
num_to_word(text)

"subject: enron methanol ; meter # : nine hundred and eighty-eight thousand, two hundred and ninety-one this is a follow up to the note i gave you on monday , four / three / zero { preliminary flow data provided by daren } . please override pop ' s daily volume { presently zero } to reflect daily activity you can obtain from gas control . this change is needed asap for economics purposes ."

# remove HTML tags

In [10]:
import re
text="Say you have some HTML that is a string: let string_of_html = ` <div>Cool</div> `; Maybe it comes from an API or you've constructed it yourself from template literals or something."
def remove_html_tag(text):
    pattern=re.compile("<.*?>")
    return pattern.sub(r" ",text)

In [11]:
remove_html_tag(text)

"Say you have some HTML that is a string: let string_of_html = `  Cool  `; Maybe it comes from an API or you've constructed it yourself from template literals or something."

In [12]:
df['text']=df['text'].apply(remove_html_tag)

In [13]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  subject: photoshop , windows , office . cheap ...   
4        2030   ham  subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [14]:
df1=pd.read_csv('Fake.csv')
df1.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

# Rmove URL

In [15]:
df2=pd.read_json('News_Category_Dataset_v3.json',lines=True)
df2.head()

link  \
0  https://www.huffpost.com/entry/covid-boosters-...   
1  https://www.huffpost.com/entry/american-airlin...   
2  https://www.huffpost.com/entry/funniest-tweets...   
3  https://www.huffpost.com/entry/funniest-parent...   
4  https://www.huffpost.com/entry/amy-cooper-lose...   

                                            headline   category  \
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   
3  The Funniest Tweets From Parents This Week (Se...  PARENTING   
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS   

                                   short_description               authors  \
0  Health experts said it is too early to predict...  Carla K. Johnson, AP   
1  He was subdued by passengers and crew when he ...        Mary Papenfuss   
2  "Until you have a dog you don't understand wha...         Elyse Wanshel   
3  "Accidentally put grown-up toothpaste on my to...      Caroline Bologna   
4  Amy Cooper accused investment firm Franklin Te...        Nina Golgowski   

        date  
0 2022-09-23  
1 2022-09-23  
2 2022-09-23  
3 2022-09-23  
4 2022-09-22

In [16]:
df2['authors_link']=df2['authors']+df2['link']
text1=df2['authors_link'][0]
text1

'Carla K. Johnson, APhttps://www.huffpost.com/entry/covid-boosters-uptake-us_n_632d719ee4b087fae6feaac9'

In [17]:
df2.head()

link  \
0  https://www.huffpost.com/entry/covid-boosters-...   
1  https://www.huffpost.com/entry/american-airlin...   
2  https://www.huffpost.com/entry/funniest-tweets...   
3  https://www.huffpost.com/entry/funniest-parent...   
4  https://www.huffpost.com/entry/amy-cooper-lose...   

                                            headline   category  \
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   
3  The Funniest Tweets From Parents This Week (Se...  PARENTING   
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS   

                                   short_description               authors  \
0  Health experts said it is too early to predict...  Carla K. Johnson, AP   
1  He was subdued by passengers and crew when he ...        Mary Papenfuss   
2  "Until you have a dog you don't understand wha...         Elyse Wanshel   
3  "Accidentally put grown-up toothpaste on my to...      Caroline Bologna   
4  Amy Cooper accused investment firm Franklin Te...        Nina Golgowski   

        date                                       authors_link  
0 2022-09-23  Carla K. Johnson, APhttps://www.huffpost.com/e...  
1 2022-09-23  Mary Papenfusshttps://www.huffpost.com/entry/a...  
2 2022-09-23  Elyse Wanshelhttps://www.huffpost.com/entry/fu...  
3 2022-09-23  Caroline Bolognahttps://www.huffpost.com/entry...  
4 2022-09-22  Nina Golgowskihttps://www.huffpost.com/entry/a...

In [18]:
text2=df2['authors_link'][1]
text2

'Mary Papenfusshttps://www.huffpost.com/entry/american-airlines-passenger-banned-flight-attendant-punch-justice-department_n_632e25d3e4b0e247890329fe'

In [19]:
text3=df2['authors_link'][2]
text3

'Elyse Wanshelhttps://www.huffpost.com/entry/funniest-tweets-cats-dogs-september-17-23_n_632de332e4b0695c1d81dc02'

In [20]:
import re
def removu_url(text):
    pattern=re.compile(r"https?://\S+|www\.\S+")
    return pattern.sub(r'',text)

In [21]:
removu_url(text1)

'Carla K. Johnson, AP'

In [22]:
removu_url(text2)

'Mary Papenfuss'

In [23]:
removu_url(text3)

'Elyse Wanshel'

In [24]:
df2['authors_link']=df2['authors_link'].apply(removu_url)

In [25]:
df2.head()

link  \
0  https://www.huffpost.com/entry/covid-boosters-...   
1  https://www.huffpost.com/entry/american-airlin...   
2  https://www.huffpost.com/entry/funniest-tweets...   
3  https://www.huffpost.com/entry/funniest-parent...   
4  https://www.huffpost.com/entry/amy-cooper-lose...   

                                            headline   category  \
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   
3  The Funniest Tweets From Parents This Week (Se...  PARENTING   
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS   

                                   short_description               authors  \
0  Health experts said it is too early to predict...  Carla K. Johnson, AP   
1  He was subdued by passengers and crew when he ...        Mary Papenfuss   
2  "Until you have a dog you don't understand wha...         Elyse Wanshel   
3  "Accidentally put grown-up toothpaste on my to...      Caroline Bologna   
4  Amy Cooper accused investment firm Franklin Te...        Nina Golgowski   

        date          authors_link  
0 2022-09-23  Carla K. Johnson, AP  
1 2022-09-23        Mary Papenfuss  
2 2022-09-23         Elyse Wanshel  
3 2022-09-23      Caroline Bologna  
4 2022-09-22        Nina Golgowski

# Remove Punctuation

In [26]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  subject: photoshop , windows , office . cheap ...   
4        2030   ham  subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [27]:
import string
a=string.punctuation
a

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [28]:
df['text'][0]

"subject: enron methanol ; meter # : 988291\r\nthis is a follow up to the note i gave you on monday , 4 / 3 / 00 { preliminary\r\nflow data provided by daren } .\r\nplease override pop ' s daily volume { presently zero } to reflect daily\r\nactivity you can obtain from gas control .\r\nthis change is needed asap for economics purposes ."

In [29]:
len(df['text'][0])

327

In [35]:
# method 1 is slow compare to method 2
def remove_punc(text):
    for char in a:
        text=text.replace(char,'')
    return text

In [36]:
remove_punc(df['text'][0])

'subject enron methanol  meter   988291\r\nthis is a follow up to the note i gave you on monday  4  3  00  preliminary\r\nflow data provided by daren  \r\nplease override pop  s daily volume  presently zero  to reflect daily\r\nactivity you can obtain from gas control \r\nthis change is needed asap for economics purposes '

In [37]:
len(remove_punc(df['text'][0]))

312

In [38]:
df['text']=df['text'].apply(remove_punc)

In [39]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  subject enron methanol  meter   988291\r\nthis...   
1        2349   ham  subject hpl nom for january 9  2001\r\n see at...   
2        3624   ham  subject neon retreat\r\nho ho ho  we  re aroun...   
3        4685  spam  subject photoshop  windows  office  cheap  mai...   
4        2030   ham  subject re  indian springs\r\nthis deal is to ...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [40]:
# method 2
def remove_punc(text):
    return text.translate(str.maketrens("","",exclude))

# text normalization/chat word treatment

In [41]:
chat_words={'hlo':'Hello','hw':'How','r':'are','u':'you','wht':'What','wch':"Which","clg":'College','yr':"Years",'2moro':'Tomorrow','gnt':'Good Night',"b4":"Before",'after':"After",'otw':'On The Way',"frm":"from"}

In [53]:
chat_words['hlo']

'Hello'

In [55]:
def chat_conversion(text):
    new_text=[]
    for w in text.split():
        if w in chat_words:
            new_text.append(chat_words[w])
        else:
            new_text.append(w)
    return ' '.join(new_text)
text='hlo , hw r u ? My name is amarendra kumar kushwaha and frm Bihar'
chat_conversion(text)

'Hello , How are you ? My name is amarendra kumar kushwaha and from Bihar'

In [56]:
text1='ok bye gnt'

In [57]:
chat_conversion(text1)

'ok bye Good Night'

# Spelling Corrector

In [58]:
from textblob import TextBlob
incorrect_text="ceertain conditionas during seveal ggenerations are modified in the maner"
textblob=TextBlob(incorrect_text)
textblob.correct().string

'certain conditions during several generations are modified in the manner'

# Remove Stopwords

In [59]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [60]:
stopword_text='certain conditions during several generations are modified in the manner'

In [61]:
len(stopword_text)

72

In [64]:
new_list=[]
def remove_stopword(text):
    for w in text.split():
        if w in stopwords.words('english'):
            new_list.append('')
        else:
            new_list.append(w)
    return ' '.join(new_list)
#     x=new_list[:]
#     new_list.clear()
#     return " ".join(x)

In [65]:
remove_stopword(stopword_text)

'certain conditions  several generations  modified   manner'

In [66]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  subject enron methanol  meter   988291\r\nthis...   
1        2349   ham  subject hpl nom for january 9  2001\r\n see at...   
2        3624   ham  subject neon retreat\r\nho ho ho  we  re aroun...   
3        4685  spam  subject photoshop  windows  office  cheap  mai...   
4        2030   ham  subject re  indian springs\r\nthis deal is to ...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [67]:
len(df['text'][2])

2442

In [68]:
len(remove_stopword(df['text'][2]))

1728

In [70]:
df['text']=df['text'].apply(remove_stopword)

MemoryError: 

In [71]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  subject enron methanol  meter   988291\r\nthis...   
1        2349   ham  subject hpl nom for january 9  2001\r\n see at...   
2        3624   ham  subject neon retreat\r\nho ho ho  we  re aroun...   
3        4685  spam  subject photoshop  windows  office  cheap  mai...   
4        2030   ham  subject re  indian springs\r\nthis deal is to ...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

# Tokenization

In [72]:
# simple way word tokenization
name='my name is amarendra kumar'
name.split()

['my', 'name', 'is', 'amarendra', 'kumar']

In [73]:
# simple way sentence tokenization
de='my name is amarendra kumar. from west cahmparan.let`s move on'
de.split('.')

['my name is amarendra kumar', ' from west cahmparan', 'let`s move on']

In [74]:
# libraries NLTK
from nltk.tokenize import word_tokenize,sent_tokenize

In [75]:
word_tokenize(de)

['my',
 'name',
 'is',
 'amarendra',
 'kumar',
 '.',
 'from',
 'west',
 'cahmparan.let',
 '`',
 's',
 'move',
 'on']

In [76]:
sent_tokenize("Narendra Damodardas Modi is an Indian politician who has served as the 14th prime minister of India since May 2014. Modi was the Chief Minister of Gujarat from 2001 to 2014 and is the Member of Parliament for Varanasi.")

['Narendra Damodardas Modi is an Indian politician who has served as the 14th prime minister of India since May 2014.',
 'Modi was the Chief Minister of Gujarat from 2001 to 2014 and is the Member of Parliament for Varanasi.']

In [77]:
str1='I have Ph.D in A.I'
str2='we`re here to help! mail us at amarendrakumar@gmail.com '
str3='A 10km ride cost $19.50'

In [78]:
# here nltk not much more compare to spacy
word_tokenize(str1)  # ok

['I', 'have', 'Ph.D', 'in', 'A.I']

In [79]:
sent_tokenize(str1)

['I have Ph.D in A.I']

In [80]:
word_tokenize(str2) # failed mail id to do split but mail is are send to model single

['we',
 '`',
 're',
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'amarendrakumar',
 '@',
 'gmail.com']

In [81]:
sent_tokenize(str2)

['we`re here to help!', 'mail us at amarendrakumar@gmail.com']

In [82]:
word_tokenize(str3) # failed 10km are joined

['A', '10km', 'ride', 'cost', '$', '19.50']

In [83]:
sent_tokenize(str3)

['A 10km ride cost $19.50']

In [84]:
# with spacy good performs
import spacy
nlp=spacy.load('en_core_web_sm')

In [85]:
doc1=nlp(str1)   # all sentence converted into documents
doc2=nlp(str2)
doc3=nlp(str3)

In [86]:
for token in doc1:
    print(token)

I
have
Ph
.
D
in
A.I


In [87]:
for token in doc2:
    print(token)

we`re
here
to
help
!
mail
us
at
amarendrakumar@gmail.com


In [88]:
for token in doc3:
    print(token)

A
10
km
ride
cost
$
19.50


# Stemming

In [89]:
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize,sent_tokenize
ps=PorterStemmer()

In [90]:
def stemm_words(text):
    return ' '.join((ps.stem(word)) for word in word_tokenize(text))

In [91]:
sample='walk walks walked walking and read reads reading'
stemm_words(sample)

'walk walk walk walk and read read read'

In [92]:
str4="Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[b] is an Indian politician who has served as the 14th prime minister of India since May 2014. Modi was the Chief Minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister from outside the Indian National Congress"

In [93]:
stemm_words(str4)

'narendra damodarda modi ( gujarati : [ ˈnəɾendɾə dɑmodəɾˈdɑ ˈmodiː ] ⓘ ; born 17 septemb 1950 ) [ b ] is an indian politician who ha serv as the 14th prime minist of india sinc may 2014 . modi wa the chief minist of gujarat from 2001 to 2014 and is the member of parliament ( mp ) for varanasi . he is a member of the bharatiya janata parti ( bjp ) and of the rashtriya swayamsevak sangh ( rss ) , a right-w hindu nationalist paramilitari volunt organis . he is the longest-serv prime minist from outsid the indian nation congress'

# Lemmatization

In [94]:
import nltk 
import string
punctuation=string.punctuation
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer=WordNetLemmatizer()

In [95]:
sentence='He was runing and eating at same time.He has bad habit of swimming after playing long hours in the sun'
sentence_words=nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuation:
        sentence_words.remove(word)
sentence_words
print("{0:20}{1:20}".format('word','lemma'))
for word in sentence_words:
    print("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word)))

word                lemma               


LookupError: 
**********************************************************************
  Resource omw-1.4 not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('omw-1.4')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/omw-1.4

  Searched in:
    - 'C:\\Users\\Amarendra Kumar/nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\share\\nltk_data'
    - 'C:\\ProgramData\\Anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\Amarendra Kumar\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


# OHE

In [96]:
# Documentation
d1="people watch match "
d2="india people watch only indian match "
d3="people write analysis after match at social media "
d4="people are reply on comment at social media "

In [97]:
# corpus
d5=d1+d2+d3+d4
d5

'people watch match india people watch only indian match people write analysis after match at social media people are reply on comment at social media '

In [98]:
#vocabulary
vocab=d5.split()
vocab=" ".join(set(vocab))
vocab

'on match media only people watch indian at social comment analysis write are reply india after'

In [99]:
#word
vocab.split()

['on',
 'match',
 'media',
 'only',
 'people',
 'watch',
 'indian',
 'at',
 'social',
 'comment',
 'analysis',
 'write',
 'are',
 'reply',
 'india',
 'after']

# BOW (Bag of word)

In [100]:
import pandas as pd
import numpy as np
db=pd.DataFrame({"text":["people watch match","india people watch only indian match and indian people ","people write comment and analysis after match at social media only indian people ","people are reply on comment at social media "],"output":[1,1,0,0]})

In [101]:
db

text  output
0                                 people watch match       1
1  india people watch only indian match and india...       1
2  people write comment and analysis after match ...       0
3       people are reply on comment at social media        0

In [102]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [103]:
bow=cv.fit_transform(db['text'])
bow # size of vocab 4*16

<4x17 sparse matrix of type '<class 'numpy.int64'>'
	with 30 stored elements in Compressed Sparse Row format>

In [104]:
#vocab
print(cv.vocabulary_)   # here all words are represent index numbers

{'people': 12, 'watch': 15, 'match': 8, 'india': 6, 'only': 11, 'indian': 7, 'and': 2, 'write': 16, 'comment': 5, 'analysis': 1, 'after': 0, 'at': 4, 'social': 14, 'media': 9, 'are': 3, 'reply': 13, 'on': 10}


In [105]:
print(bow[0].toarray())
print(bow[1].toarray()) # some word frequency is occured
print(bow[2].toarray()) # some word frequency is occured
print(bow[3].toarray())

[[0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0]]
[[0 0 1 0 0 0 1 2 1 0 0 1 2 0 0 1 0]]
[[1 1 1 0 1 1 0 1 1 1 0 1 2 0 1 0 1]]
[[0 0 0 1 1 1 0 0 0 1 1 0 1 1 1 0 0]]


In [106]:
# for predict another sentence
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [107]:
cv.transform(["india people watch only indian match and indian people "]).toarray()

array([[0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 1, 2, 0, 0, 1, 0]], dtype=int64)

In [108]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  subject enron methanol  meter   988291\r\nthis...   
1        2349   ham  subject hpl nom for january 9  2001\r\n see at...   
2        3624   ham  subject neon retreat\r\nho ho ho  we  re aroun...   
3        4685  spam  subject photoshop  windows  office  cheap  mai...   
4        2030   ham  subject re  indian springs\r\nthis deal is to ...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [109]:
bow1=cv.fit_transform(df['text'])
bow1

<5171x50486 sparse matrix of type '<class 'numpy.int64'>'
	with 456119 stored elements in Compressed Sparse Row format>

In [110]:
bow1[0].toarray()

array([[1, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Translation and language

In [112]:
from textblob import TextBlob
blob=TextBlob("as far as my family is concerned there are seven members in my family")
blob.translate(from_lang='eng',to='hi')

TextBlob("जहां तक ​​मेरे परिवार का सवाल है, मेरे परिवार में सात सदस्य हैं")

In [113]:
blob=TextBlob("now is better than never")
blob.translate(from_lang='eng',to='hi')

TextBlob("अब कभी नहीं से बेहतर है")

# N_ Grams

In [114]:
blob=TextBlob("now is better than never")
blob.ngrams(n=3)

[WordList(['now', 'is', 'better']),
 WordList(['is', 'better', 'than']),
 WordList(['better', 'than', 'never'])]

In [115]:
db

text  output
0                                 people watch match       1
1  india people watch only indian match and india...       1
2  people write comment and analysis after match ...       0
3       people are reply on comment at social media        0

In [116]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))

In [117]:
bow2=cv.fit_transform(db['text'])
bow2

<4x24 sparse matrix of type '<class 'numpy.int64'>'
	with 29 stored elements in Compressed Sparse Row format>

In [118]:
print(cv.vocabulary_)

{'people watch': 17, 'watch match': 21, 'india people': 8, 'watch only': 22, 'only indian': 15, 'indian match': 9, 'match and': 11, 'and indian': 3, 'indian people': 10, 'people write': 18, 'write comment': 23, 'comment and': 6, 'and analysis': 2, 'analysis after': 1, 'after match': 0, 'match at': 12, 'at social': 5, 'social media': 20, 'media only': 13, 'people are': 16, 'are reply': 4, 'reply on': 19, 'on comment': 14, 'comment at': 7}


In [119]:
print(bow2[0].toarray())
print(bow2[1].toarray())
print(bow2[2].toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]]
[[0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 0 0 0 1 0]]
[[1 1 1 0 0 1 1 0 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 1]]


# TF-IDF

In [120]:
db

text  output
0                                 people watch match       1
1  india people watch only indian match and india...       1
2  people write comment and analysis after match ...       0
3       people are reply on comment at social media        0

In [121]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer()

In [122]:
tfidf=cv.fit_transform(db['text'])
tfidf.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.55953044, 0.        ,
        0.        , 0.        , 0.4574528 , 0.        , 0.        ,
        0.69113141, 0.        ],
       [0.        , 0.        , 0.3012842 , 0.        , 0.        ,
        0.        , 0.3821408 , 0.6025684 , 0.24391553, 0.        ,
        0.        , 0.3012842 , 0.39883385, 0.        , 0.        ,
        0.3012842 , 0.        ],
       [0.33618748, 0.33618748, 0.26505407, 0.        , 0.26505407,
        0.26505407, 0.        , 0.26505407, 0.21458411, 0.26505407,
        0.        , 0.26505407, 0.35087315, 0.        , 0.26505407,
        0.        , 0.33618748],
       [0.        , 0.        , 0.        , 0.41671408, 0.32854217,
        0.32854217, 0.        , 0.        , 0.        , 0.32854217,
        0.41671408, 0.        , 0.2174587 , 0.41671408, 0.32854217,
        0.        , 0.        ]])

In [123]:
# print(tfidf.idf_)
# print(tfidf.get_feature_names_out())

# POS

In [124]:
import spacy

In [125]:
nlp=spacy.load('en_core_web_sm')

In [126]:
doc=nlp("i will about facebook")
doc

i will about facebook

In [127]:
doc[0]

i

In [128]:
doc[0].pos_   # approx find out the pos

'PRON'

In [129]:
doc[0].tag_  # deeply find out the pos

'PRP'

In [130]:
doc.text

'i will about facebook'

In [133]:
for word in doc:
    print(word,"----->",word.pos_,"-->",word.tag_,"-->",spacy.explain(word.tag_),"----->",word.lemma_)

i -----> PRON --> PRP --> pronoun, personal -----> I
will -----> AUX --> MD --> verb, modal auxiliary -----> will
about -----> ADV --> RB --> adverb -----> about
facebook -----> VERB --> VB --> verb, base form -----> facebook


In [134]:
for word in doc:
    print(word.text,"----->",word.pos_,"-->",word.tag_,"-->",spacy.explain(word.tag_))

i -----> PRON --> PRP --> pronoun, personal
will -----> AUX --> MD --> verb, modal auxiliary
about -----> ADV --> RB --> adverb
facebook -----> VERB --> VB --> verb, base form


In [135]:
doc1=nlp("i left the room")
for word in doc1:
    print(word.text,"--->",word.pos_,"-->",word.tag_,'-->',spacy.explain(word.tag_))

i ---> PRON --> PRP --> pronoun, personal
left ---> VERB --> VBD --> verb, past tense
the ---> DET --> DT --> determiner
room ---> NOUN --> NN --> noun, singular or mass


In [136]:
for word in nlp("to the left of the room"):
    print(word.text,"--->",word.pos_,"-->",word.tag_,'-->',spacy.explain(word.tag_))

to ---> ADP --> IN --> conjunction, subordinating or preposition
the ---> DET --> DT --> determiner
left ---> NOUN --> NN --> noun, singular or mass
of ---> ADP --> IN --> conjunction, subordinating or preposition
the ---> DET --> DT --> determiner
room ---> NOUN --> NN --> noun, singular or mass


In [137]:
for word in nlp("I read a book on history"):
    print(word.text,"--->",word.pos_,"-->",word.tag_,'-->',spacy.explain(word.tag_))

I ---> PRON --> PRP --> pronoun, personal
read ---> VERB --> VBD --> verb, past tense
a ---> DET --> DT --> determiner
book ---> NOUN --> NN --> noun, singular or mass
on ---> ADP --> IN --> conjunction, subordinating or preposition
history ---> NOUN --> NN --> noun, singular or mass


In [138]:
for word in nlp("I have read a book on history"):
    print(word.text,"--->",word.pos_,"-->",word.tag_,'-->',spacy.explain(word.tag_))

I ---> PRON --> PRP --> pronoun, personal
have ---> AUX --> VBP --> verb, non-3rd person singular present
read ---> VERB --> VBN --> verb, past participle
a ---> DET --> DT --> determiner
book ---> NOUN --> NN --> noun, singular or mass
on ---> ADP --> IN --> conjunction, subordinating or preposition
history ---> NOUN --> NN --> noun, singular or mass


In [139]:
# Visualization
doc5=nlp("Narendra Damodardas Modi is an Indian politician who has served as the 14th prime minister of India since May 2014. Modi was the Chief Minister of Gujarat from 2001 to 2014 and is the Member of Parliament for Varanasi.")

In [140]:
doc4=nlp('My name is amarendra kumar kushwaha from west champaran Bihar')

In [141]:
from spacy import displacy

In [142]:
displacy.render(doc4,style='dep',jupyter=True)

In [143]:
options={"distance":90,
        "compact":True,
        "color":'#rr',
        "bg":"#00a65"}

In [144]:
displacy.render(doc4,style='dep',jupyter=True,options=options)

# Text Classification

In [145]:
import pandas as pd
import numpy as np

In [146]:
df=pd.read_csv('IMBD.csv')
df.head()

text  label
0  I grew up (b. 1965) watching and loving the Th...      0
1  When I put this movie in my DVD player, and sa...      0
2  Why do people who do not know what a particula...      0
3  Even though I have great interest in Biblical ...      0
4  Im a die hard Dads Army fan and nothing will e...      1

In [147]:
df.shape

(40000, 2)

In [148]:
df.isnull().sum()

text     0
label    0
dtype: int64

In [149]:
df.duplicated().sum()

277

In [150]:
df = df.drop_duplicates(subset=['text'])
df.duplicated().sum()

0

In [151]:
df['text'][1]

"When I put this movie in my DVD player, and sat down with a coke and some chips, I had some expectations. I was hoping that this movie would contain some of the strong-points of the first movie: Awsome animation, good flowing story, excellent voice cast, funny comedy and a kick-ass soundtrack. But, to my disappointment, not any of this is to be found in Atlantis: Milo's Return. Had I read some reviews first, I might not have been so let down. The following paragraph will be directed to those who have seen the first movie, and who enjoyed it primarily for the points mentioned.<br /><br />When the first scene appears, your in for a shock if you just picked Atlantis: Milo's Return from the display-case at your local videoshop (or whatever), and had the expectations I had. The music feels as a bad imitation of the first movie, and the voice cast has been replaced by a not so fitting one. (With the exception of a few characters, like the voice of Sweet). The actual drawings isnt that bad, 

In [152]:
#convert lowercase
df['text']=df['text'].apply(lambda x:x.lower())

In [153]:
df.head()

text  label
0  i grew up (b. 1965) watching and loving the th...      0
1  when i put this movie in my dvd player, and sa...      0
2  why do people who do not know what a particula...      0
3  even though i have great interest in biblical ...      0
4  im a die hard dads army fan and nothing will e...      1

In [154]:
#remove HTML tag
import re
def remove_htmltag(text):
    clean_text=re.sub(re.compile("<.*?>"),"",text)
    return clean_text

In [155]:
df['text']=df['text'].apply(remove_htmltag)

In [156]:
df['text'][1]

"when i put this movie in my dvd player, and sat down with a coke and some chips, i had some expectations. i was hoping that this movie would contain some of the strong-points of the first movie: awsome animation, good flowing story, excellent voice cast, funny comedy and a kick-ass soundtrack. but, to my disappointment, not any of this is to be found in atlantis: milo's return. had i read some reviews first, i might not have been so let down. the following paragraph will be directed to those who have seen the first movie, and who enjoyed it primarily for the points mentioned.when the first scene appears, your in for a shock if you just picked atlantis: milo's return from the display-case at your local videoshop (or whatever), and had the expectations i had. the music feels as a bad imitation of the first movie, and the voice cast has been replaced by a not so fitting one. (with the exception of a few characters, like the voice of sweet). the actual drawings isnt that bad, but the anim

In [157]:
#remove punctuation
import string
a=string.punctuation
a

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [158]:
def remove_punctuation(text):
    for word in a:
        text=text.replace(word,'')
    return text

In [159]:
df['text']=df['text'].apply(remove_punctuation)
df['text'][1]

'when i put this movie in my dvd player and sat down with a coke and some chips i had some expectations i was hoping that this movie would contain some of the strongpoints of the first movie awsome animation good flowing story excellent voice cast funny comedy and a kickass soundtrack but to my disappointment not any of this is to be found in atlantis milos return had i read some reviews first i might not have been so let down the following paragraph will be directed to those who have seen the first movie and who enjoyed it primarily for the points mentionedwhen the first scene appears your in for a shock if you just picked atlantis milos return from the displaycase at your local videoshop or whatever and had the expectations i had the music feels as a bad imitation of the first movie and the voice cast has been replaced by a not so fitting one with the exception of a few characters like the voice of sweet the actual drawings isnt that bad but the animation in particular is a sad sight

In [160]:
# remove stopwords
from nltk.corpus import stopwords
stop_word=stopwords.words('english')

In [161]:
def remove_stop(text):
    new_list=[]
    for word in text.split():
        if word in stop_word:
            new_list.append("")
        else:
            new_list.append(word)
    x=new_list[:]
    new_list.clear()
    return ' '.join(x)

In [162]:
remove_stop(df['text'][1])

'  put  movie   dvd player  sat    coke   chips    expectations   hoping   movie would contain    strongpoints   first movie awsome animation good flowing story excellent voice cast funny comedy   kickass soundtrack    disappointment        found  atlantis milos return   read  reviews first  might     let   following paragraph   directed     seen  first movie   enjoyed  primarily   points mentionedwhen  first scene appears     shock    picked atlantis milos return   displaycase   local videoshop  whatever    expectations    music feels   bad imitation   first movie   voice cast   replaced     fitting one   exception    characters like  voice  sweet  actual drawings isnt  bad   animation  particular   sad sight  storyline  also pretty weak    like three episodes  schoobydoo   single adventurous story  got  last time  dont misunderstand    good schoobydoo episodes  didnt laugh  single time although  might  sniggered   twiceto  audience  havent seen  first movie  dont especially care   si

In [163]:
df['text']=df['text'].apply(remove_stop)

In [164]:
df.head()

text  label
0   grew  b 1965 watching  loving  thunderbirds  ...      0
1    put  movie   dvd player  sat    coke   chips...      0
2    people    know   particular time   past  lik...      0
3  even though   great interest  biblical movies ...      0
4  im  die hard dads army fan  nothing  ever chan...      1

In [165]:
import gensim
from gensim.utils import simple_preprocess
from nltk import word_tokenize

In [166]:
story=[]
for word in df['text']:
    raw_token=word_tokenize(word)
    for sent in raw_token:
        story.append(simple_preprocess(sent))

In [167]:
# model building
model=gensim.models.Word2Vec(window=10,min_count=2)

In [168]:
model.build_vocab(story)

In [169]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(22162580, 23530270)

In [170]:
len(model.wv.index_to_key)

71284

In [171]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [172]:
document_vector(df['text'].values[0])

array([-1.5413602e-03, -6.8680587e-04,  2.0780174e-04,  6.1495136e-04,
       -6.6092401e-04,  2.4898801e-04,  5.6651077e-04,  3.7519643e-04,
        8.2804399e-05, -1.0818314e-03, -4.4155386e-04,  8.5565721e-04,
        1.4961913e-03, -1.4691087e-04, -2.2843044e-04,  4.4781284e-04,
        1.3540259e-03,  5.8862614e-04,  9.8502042e-04,  1.5660741e-04,
       -1.6279153e-04,  1.2407857e-03,  1.2117448e-03,  7.6947668e-05,
        9.6846645e-04, -5.0730602e-04,  3.5074854e-04, -3.0091745e-04,
       -6.1348407e-04,  3.0530275e-05, -5.2040222e-04,  1.4242828e-03,
       -9.8032819e-04,  1.8567579e-04, -8.1276865e-04, -1.0975750e-04,
       -2.4021117e-04, -9.4440964e-04,  8.3677536e-05, -8.2495820e-04,
       -1.9419035e-04, -8.3265814e-04, -1.2558179e-03, -9.7799813e-04,
        7.5869571e-04, -3.3779690e-04,  5.9378869e-04, -1.0401580e-03,
       -4.0196560e-04,  5.5941235e-04, -1.3277042e-04, -1.0550117e-04,
       -4.3185556e-04,  4.5773049e-04,  6.0488493e-04, -9.4023847e-04,
      

In [173]:
from tqdm import tqdm

In [ ]:
X = []
for doc in tqdm(df['text'].values):
    X.append(document_vector(doc))

 29%|█████████████████████▌                                                    | 11607/39723 [12:32<4:26:28,  1.76it/s]

In [ ]:
X = np.array(X)

In [ ]:
X[0]

In [ ]:
y=df['label']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)

In [ ]:
y_pred = nb.predict(X_test)
accuracy_score(y_test,y_pred)

In [ ]:
print("Naive Bayes score: ",nb.score(X_test, y_test))

# NER

In [ ]:
import spacy
from spacy import displacy
from spacy import tokenizer
nlp = spacy.load('en_core_web_sm')

In [ ]:
text =("Python is an interpreted, high-level and general-purpose programming language "
       "Pythons design philosophy emphasizes code readability with"
       "its notable use of significant indentation."
       "Its language constructs and object-oriented approach aim to"
       "help programmers write clear and"
       "logical code for small and large-scale projects")

In [ ]:
doc = nlp(text)
sentences = list(doc.sents)
print(sentences)

In [ ]:
doc

In [ ]:
for e in doc.ents:
    print(e)

In [ ]:
for token in doc:
    print(token.text)
ents = [(e.text, e.start_char, e.end_char, e.label_) for e in doc.ents]
print(ents)
displacy.render(doc, style='ent', jupyter=True)