In [1]:
import tensorflow as tf

In [11]:
tf.__version__

'2.12.0'

In [12]:
hello_constant=tf.constant('Hello world')
hello_constant

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello world'>

In [13]:
hello_constant=tf.constant(4,5,4,3)
hello_constant

<tf.Tensor: shape=(4,), dtype=int16, numpy=array([4, 4, 4, 4], dtype=int16)>

In [14]:
B=tf.constant([[1,2,3,4],[3,4,5,7]])
B

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [3, 4, 5, 7]])>

In [15]:
# array elements can not be same so in that case getting the error
B=tf.constant([[1,2,3,4],[3,4,5]])
B

ValueError: Can't convert non-rectangular Python sequence to Tensor.

# Addition

In [16]:
x=tf.add(5,2)
print(x)

tf.Tensor(7, shape=(), dtype=int32)


In [17]:
x=5+2
type(x)

int

In [18]:
x=tf.subtract(10,4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [19]:
y=tf.multiply(2,5)
y

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [20]:
tf.add(5,2)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [21]:
tf.subtract(10,4)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [22]:
import tensorflow as tf
x=tf.constant(10)
y=tf.constant(2)
z=tf.subtract(tf.divide(x,y),1)  # subtract means(5,1)
z

<tf.Tensor: shape=(), dtype=float64, numpy=4.0>

In [23]:
tf.divide(x,y)

<tf.Tensor: shape=(), dtype=float64, numpy=5.0>

In [36]:
# cast is the type casting(converted datatype)
tf.subtract(tf.cast(tf.constant(2.0),tf.int32),tf.constant(1))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

# tensorflow 
# Datatype
1. constant  > in case of creation pass the variable at run time .(can not be change through out the program)
2. placeholder  > but in case of placeholder pass the datatype at run time.
3. variable     >. initialize the data and letter stage sometime changes

In [26]:
x=tf.placeholder(tf.string)
y=tf.placeholder(tf.int32)
z=tf.placeholder(tf.float32)
with tf.session() as sess:
    out_x=sess.run(x,fee_dict={x:'hello world',y:2345,z:234.85})
    out_y=sess.run(x,fee_dict={x:'hello world',y:2345,z:234.85})
    out_z=sess.run(x,fee_dict={x:'hello world',y:2345,z:234.85})
    print(out_sess)
    print(out_sess)

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [27]:
x=tf.Variable(5)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>

# tensorflow softmax function
>. the softmax function squashes its inputs . typically called logits or logit scores . to be 0 or 1 and 
  also normalize the outputs such that they all sum to 1. This means output of the softmax function is eqivalent to a categorical probability distributions.its the perfect function to use as the output activation for a network predicting multiple cllasses

In [28]:
x=tf.nn.softmax([2.0,1.0,0.2])
x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.65223986, 0.23994564, 0.10781453], dtype=float32)>

# One Hot Encoding (categorical data convert into numerical )
> In this case we have to check out the how many distinct variable in the feature,
  after all the distinct variable are create seperate - seperate features ,
> > we have to assigned the data all feature that is label encoding.
> > then we have to represent the data bit( 1,0) bitwise represent (active =1,  Deactive=0)

In [29]:
import tensorflow as tf
import numpy as np
from sklearn import preprocessing 
## Example labels
labels=np.array([1,5,3,2,1,4,2,1,3])
# create the encoder
lb=preprocessing.LabelBinarizer()

# Here the  encoder finds the classes and assigns one-hot vectors
lb.fit(labels)

# And finally, transform the labels into one- hot encoded vectors
lb.transform(labels)


array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]])

# tensorflow cross entropy
# tow function
1. tf.reduce_sum()
2. tf.log()

# 1. Reduce function

In [30]:
y=[1,2,3,4,5]
sum(y)

15

In [31]:
x=tf.reduce_sum([1,2,3,4,5])
x

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [32]:
l=tf.log(100)

AttributeError: module 'tensorflow' has no attribute 'log'

# random constant

In [ ]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

In [ ]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

# Declaring variables

In [ ]:
var0=24
var1=tf.Variable(42)
var2=tf.Variable([ [ [0.,1.,2.],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.] ] ])
var0,var1,var2

# To ressign a variable  , ues var.assign()

In [ ]:
x=tf.constant(1)
x

In [33]:
var_reassingn=tf.Variable(89)
var_reassingn

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=89>

# Rank of a Tensor
> the rank of a tensor is defined as the number of dimension , which is the numbers of indices that are required to specify any particular element of that tensor.

# Transpose Matrix Multiplication

In [25]:
matrix_u=tf.constant([[6,7,6]])
matrix_v=tf.constant([[3,4,3]])
tf.matmul(matrix_u,tf.transpose(matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[64]])>

# casting a tensor to another datatype
> change the datatype

In [26]:
j=tf.cast(tf.constant(4.9),dtype=tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

# Ragged Tensor
> A ragged tensor is a tensor having one or  more ragged dimmensions. Ragged dimensions are dimensions that have slices having various lenghts. there are avariety of methods for the declarations of ragged arrays, the simplest way is declaring a constant.

In [27]:
ragged=tf.ragged.constant([[9,7,4,3],[],[11,12,8],[3],[7,8]])
print(ragged)
print(ragged[0,:1])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>
tf.Tensor([9], shape=(1,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([11 12  8], shape=(3,), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)


# calculate the mean

In [28]:
numbers=tf.constant([[8.,9.],[1.,2.]])   ## sum of all the no

In [29]:
tf.reduce_mean(numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [30]:
tf.reduce_mean(numbers,axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

In [31]:
tf.reduce_mean(numbers,axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.5, 1.5], dtype=float32)>

In [32]:
x=tf.random.normal(shape=(3,2),mean=10,stddev=2,dtype=tf.float32,seed=None,name=None)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 9.241884,  8.647889],
       [ 8.117116,  6.518938],
       [ 8.641759, 12.02896 ]], dtype=float32)>

In [33]:
y=tf.cast(x,dtype=tf.int32)
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9,  8],
       [ 8,  6],
       [ 8, 12]])>

In [34]:
dice1=tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
dice2=tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))

# Lets ADD
dice_sum1=dice1+dice2

final_matrix=tf.concat(values=[dice1,dice2,dice_sum1],axis=1)
final_matrix

<tf.Tensor: shape=(10, 3), dtype=int32, numpy=
array([[2, 2, 4],
       [4, 5, 9],
       [3, 5, 8],
       [2, 6, 8],
       [6, 1, 7],
       [6, 3, 9],
       [2, 5, 7],
       [3, 3, 6],
       [5, 3, 8],
       [5, 3, 8]])>

# TensorFlow Linear Regression

In [38]:
# y=xw+b
# tf.Variable()

In [40]:
tf.Variable(5)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>

In [2]:
import pandas as pd 
import numpy as np

In [14]:
#Load datasets
df=pd.read_csv('C:/Users/Amarendra Kumar/Desktop/Housing.csv',delim_whitespace=True,header=None)
df.shape

(546, 1)

In [18]:
# datasets converted into array
datasets=df.values
datasets
# split the data input (x) into output(y)
X=datasets[:,0:13]
Y=datasets[:,13]

IndexError: index 13 is out of bounds for axis 1 with size 1